# Generated by Django 4.2.5 on 2023-09-25 10:05

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='before_date',
            new_name='apply_before',
        ),
        migrations.AlterField(
            model_name='apply',
            name='expected_start_date',
            field=models.DateField(validators=[app.models.validate_date]),
        ),
    ]
