# Generated by Django 4.2.5 on 2023-09-22 11:38

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_post_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='expected_start_date',
            field=models.DateTimeField(validators=[app.models.validate_apply_date]),
        ),
        migrations.AlterField(
            model_name='apply',
            name='learning_institution',
            field=models.CharField(choices=[('Learning institution', 'Learning institution'), ('Moi university', 'Moi university'), ('kenyatta university', 'Kenyatta university'), ('University of Nairobi', 'University of Nairobi'), ('Chuka university', 'Chuka university'), ('Egerton university', 'Egerton university'), ('University of Eldoret', 'University of Eldoret')], default='Learning institution', max_length=100),
        ),
    ]
