# Generated by Django 4.2.5 on 2023-09-25 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_before_date_post_apply_before_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='expected_start_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_start_date', to='app.post'),
        ),
    ]
