# Generated by Django 4.2.5 on 2023-09-25 11:22

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_apply_expected_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='expected_start_date',
            field=models.DateField(validators=[app.models.validate_date]),
        ),
    ]
