# Generated by Django 4.2.5 on 2023-09-27 10:12

import app.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_apply_expected_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='application_date',
            field=models.DateField(default='2023-09-27', verbose_name=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apply',
            name='expected_start_date',
            field=models.DateField(validators=[app.models.validate_expected_start_date]),
        ),
    ]
