# Generated by Django 4.2.5 on 2023-09-22 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_post_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='expected_start_date',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
