# Generated by Django 4.2.5 on 2023-10-01 06:09

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_apply_application_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='application_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='apply',
            name='expected_start_date',
            field=models.DateField(blank=True, null=True, validators=[app.models.validate_expected_start_date]),
        ),
        migrations.AlterField(
            model_name='apply',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
