# Generated by Django 4.2.5 on 2023-09-25 06:53

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_apply_expected_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='start_date',
            field=models.DateField(validators=[app.models.validate_start_date]),
        ),
    ]
