# Generated by Django 4.2.5 on 2023-10-01 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_alter_apply_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='learning_institution',
            field=models.CharField(choices=[('Learning institution', 'Learning institution'), ('Moi university', 'Moi university'), ('kenyatta university', 'Kenyatta university'), ('University of Nairobi', 'University of Nairobi'), ('Chuka university', 'Chuka university'), ('Egerton university', 'Egerton university'), ('University of Eldoret', 'University of Eldoret')], max_length=100),
        ),
        migrations.AlterField(
            model_name='apply',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
