# Generated by Django 4.2.5 on 2023-10-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_apply_learning_institution_alter_apply_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
