# Generated by Django 4.2.5 on 2023-10-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_apply_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='learning_institution',
            field=models.CharField(choices=[('Moi university', 'Moi university'), ('kenyatta university', 'Kenyatta university'), ('University of Nairobi', 'University of Nairobi'), ('Chuka university', 'Chuka university'), ('Egerton university', 'Egerton university'), ('University of Eldoret', 'University of Eldoret')], max_length=100),
        ),
    ]
